runtime: python39
entrypoint: python app.py

instance_class: F1
automatic_scaling:
  max_instances: 5
  min_instances: 1
  max_pending_latency: 10s

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'credhere'
  OPENAI_API_KEY: 'pastekeyhere'